export type BilingualTextValue = {
  en: string
  th: string
}

// Mobile-only: recruitment pool candidate (see data/recruitment.ts).
export type RecruitmentTier = 'rookie' | 'skilled' | 'expert' | 'star'

export type RecruitmentCandidate = {
  id: string
  type: WorkerType
  name: string
  tier: RecruitmentTier
  startingLevel: number
  cost: number
  isVeteran: boolean
}

// Product types — gasoline is primary. asphalt, jetFuel, lubricants, petrochemicals are secondary products.
export type ProductKey = 'gasoline' | 'asphalt' | 'jetFuel' | 'lubricants' | 'petrochemicals' | 'recycledMaterial' | 'plasticPellets'

export type ProductInventory = Record<ProductKey, number>

export type BuildingType =
  | 'crudeTank'
  | 'distillationUnit'
  | 'productTank'
  | 'laboratory'
  | 'maintenanceWorkshop'
  | 'salesOffice'
  | 'lubricantPlant'
  | 'jetFuelPlant'
  | 'petrochemicalPlant'
  | 'powerPlant'
  | 'wasteTreatmentPlant'
  | 'polymerPlant'
  | 'lubricantTank'
  | 'jetFuelTank'
  | 'petrochemicalTank'
  | 'recyclingBunker'
  | 'pelletSilo'

export type GridCell = BuildingType | null

export type GameState = {
  money: number
  researchPoints: number
  reputation: number
  crudeOil: number
  gasoline: number
  // Intermediate refined feedstock: Distillation Units make it from crude;
  // downstream plants (jet fuel / lubricants / petrochemicals) consume it.
  feedstock: number
  // Production Complexity Expansion Phase 2: electricity generated by Power
  // Plants (burn crude), consumed by downstream production plants. When at
  // least 1 Power Plant is built and supply < demand, downstream plant
  // output is throttled (folded into the existing feedstock shareRatio).
  electricity: number
  // Production Complexity Expansion Phase 1: waste byproduct from "dirty"
  // production buildings. Over-cap waste applies an ESG penalty. See
  // WASTE_BALANCE.
  waste: number
  // Phase A foundation: future product inventory.
  // Only gasoline is active. Others are unused placeholders.
  // game.gasoline remains the source of truth for all current gameplay.
  productInventory: ProductInventory
  refineryLevel: number
  productionProgress: number
  tickCount: number
  lastEventMessage: string
  totalGasolineProduced: number
  completedContractCount: number
  totalWorkersHired: number
  unlockedResearchCount: number
  activityLog: string[]
  completedContractIds: number[]
  completedMilestoneKeys: MilestoneKey[]
  unlockedResearchIds: ResearchKey[]
  workerCounts: WorkerCounts
  // System 1: Staff Training & Levels (Individual Staff) — one entry per
  // hired worker, in hire order. Invariant: for every WorkerType,
  // employees.filter(e => e.type === type).length === workerCounts[type].
  employees: Employee[]
  // Per-Plant Staff Assignment (design doc Part A, replaces the old
  // shared-pool model): maps a grid cellIndex -> the employeeId assigned
  // to that specific plant instance. An employee can be assigned to at
  // most 1 cell; a cell can have at most 1 assigned employee. Only cells
  // whose building has a specialistWorker (jetFuelPlant ->
  // aviationSpecialist, petrochemicalPlant -> chemicalEngineer,
  // polymerPlant -> polymerEngineer) are valid keys -- enforced by the
  // assignEmployeeToCell action, not by the type. Unassigned plants (no
  // entry for that cellIndex) get no specialist bonus.
  assignments: Record<number, string>
  // Mobile-only: recruitment pool ("3 candidates apply, pick one" hiring
  // flow). See data/recruitment.ts. recruitmentRefreshAt is the tickCount
  // at which the whole pool auto-refreshes; recruitmentNameCounter is a
  // monotonic counter so candidate names cycle through STAFF_NAME_POOL
  // independently of actual hires.
  recruitmentPool: RecruitmentCandidate[]
  recruitmentRefreshAt: number
  recruitmentNameCounter: number
  // Mobile-only: tickCount when a choice event was last shown (milestone-
  // triggered or fallback). Drives the fallback timer -- see
  // CHOICE_EVENT_FALLBACK_TICKS in useGameLoop.ts.
  lastChoiceEventTick: number
  // Mobile-only: 🔥 Boost button state. While tickCount < boostActiveUntilTick,
  // gasoline production runs at BOOST_BALANCE.productionMultiplier speed.
  // boostAvailableAtTick is the tick at which the button is usable again
  // (set on activation, includes the active duration).
  boostActiveUntilTick: number
  boostAvailableAtTick: number
  // ESG/Safety axis: 0-100 score. Drifts each tick (down from "dirty"
  // buildings, up from safetyOfficer staff). High score reduces incident-
  // event chance and unlocks a premium contract bonus; low score raises
  // incident-event chance. See ESG_BALANCE.
  esgScore: number
  // Strategic Differentiation #2 (Energy Transition era): demand multipliers
  // that drift once the energyTransition era is reached -- gasoline demand
  // falls toward gasolineDemandFloor, petrochemicals demand rises toward
  // petrochemicalsDemandCeiling. Both start at 1.0 and are monotonic (never
  // reverse). See DEMAND_SHIFT_BALANCE.
  gasolineDemandMultiplier: number
  petrochemicalsDemandMultiplier: number
  // Perk Diversity Pass: fractional carry-over for the Efficiency branch's
  // gasoline-yield bonus (perkProductionBonusRate). Without this, a +10%
  // yield on small per-tick batch counts would round away to nothing every
  // tick; the carry lets it average out correctly over time.
  gasolineYieldCarry: number
  // Keys of HIDDEN_COMBOS already discovered/rewarded (one-time each).
  discoveredCombos: string[]
  // Hidden Event system (separate from discoveredCombos above): keys of
  // HiddenEventConfig entries that have been unlocked (condition met) OR
  // claimed. Unlocked-but-not-yet-claimed events are tracked the same way
  // claimed ones are -- see hiddenEventState below for which is which.
  // Once a key is in this array its trigger condition is never
  // re-evaluated (so a one-time event can't re-trigger after being
  // claimed and its condition becomes true again later).
  discoveredHiddenEvents: string[]
  // For each discoveredHiddenEvents key: 'unlocked' (condition met, "???"
  // card showing, not yet claimed -- stays this way indefinitely, no
  // deadline) or 'claimed' (player tapped to reveal + take the reward).
  hiddenEventStatus: Partial<Record<string, 'unlocked' | 'claimed'>>
  // Remaining free/discounted placements for a claimed 'building'-reward
  // Hidden Event, keyed by BuildingType. Decremented each time the player
  // places that building while uses remain; the build picker shows it as
  // a special option only while count > 0.
  hiddenBuildingUsesRemaining: Partial<Record<BuildingType, number>>
  // Contracts granted by a claimed 'contract'-reward Hidden Event. Kept
  // separate from the static CONTRACTS array (which never changes at
  // runtime) -- the contracts UI/derived stats merge this in alongside
  // CONTRACTS so claimed hidden contracts show up and are completable
  // exactly like normal ones, just sourced from here instead.
  hiddenContracts: Contract[]
  // System 2: Refinery Upgrade Perk Tree
  upgradePoints: number
  unlockedPerks: PerkKey[]
  // System 3: Tech Eras (highestEraIndex drives the "new era" banner)
  highestEraIndex: number
  // System 4: Annual Awards
  businessYear: number
  yearStartTick: number
  yearStats: YearStats
  awardHistory: AwardRecord[]
  grid: GridCell[]
  gridLevels: number[]
  gridExpansionLevel: number
  prototypeCompleted: boolean
  everBoughtCrude: boolean
  starterGuideDismissed: boolean
  // Player-chosen name for their refinery, shown in the hero panel alongside
  // a level-based title (see getRefineryTitle).
  refineryName: string
  pendingShipments: PendingShipment[]
  // Maps standing order key → tick at which the order becomes available again.
  // Absent key means the order is currently available (never fulfilled or cooldown expired).
  standingOrderCooldowns: Partial<Record<StandingOrderKey, number>>
  // Feedstock Priority: per-downstream-plant weight (0 to
  // FEEDSTOCK_PRIORITY_BALANCE.max, in FEEDSTOCK_PRIORITY_BALANCE.step
  // increments, default 1 = 100%) used when feedstock is scarce -- a
  // higher weight gets a larger share of the proportional split (see
  // tick()). 0 = fully off (this plant never produces, regardless of
  // feedstock availability). Has no effect when feedstock supply covers
  // total demand -- every plant still gets its normal full output then.
  feedstockPriority: Record<'lubricantPlant' | 'jetFuelPlant' | 'petrochemicalPlant', number>
}

export type BuildingConfig = {
  name: BilingualTextValue
  shortName: string
  cost: number
  description: BilingualTextValue
  unlockLevel?: number
}

export type ComboStats = {
  crudeToDistillation: number
  distillationToProduct: number
  crudeToProduct: number
}

export type Contract = {
  id: number
  name: BilingualTextValue
  tier: 1 | 2 | 3
  unlockLevel: number
  gasolineRequired: number
  // Phase B: asphalt contracts use this field instead of gasolineRequired
  asphaltRequired?: number
  // Phase C: jet fuel contracts
  jetFuelRequired?: number
  // Phase D: lubricant contracts
  lubricantsRequired?: number
  // Phase E: petrochemical contracts
  petrochemicalsRequired?: number
  // Phase F: recycled material contracts (from Waste Treatment Plant)
  recycledMaterialRequired?: number
  // Phase G: plastic pellets contracts (from Polymer Plant)
  plasticPelletsRequired?: number
  reward: number
  rpReward: number
  reputationReward: number
}

export type ActiveContract = Contract & {
  isCompleted: boolean
  isUnlocked: boolean
  currentReward: number
  currentRpReward: number
  currentReputationReward: number
  unlockRequirement?: BilingualTextValue
}

export type ReputationTier = {
  name: BilingualTextValue
  minimumReputation: number
  contractRewardBonusRate: number
}

export type ResearchKey =
  | 'betterPumps'
  | 'biggerTanks'
  | 'premiumFuel'
  | 'advancedDistillation'
  | 'industrialStorage'
  | 'premiumContracts'
  | 'advancedProcessing'
  | 'storageOptimization'
  | 'contractAnalytics'
  | 'saferOperations'

export type ResearchItem = {
  key: ResearchKey
  name: BilingualTextValue
  cost: number
  description: BilingualTextValue
  prerequisite?: ResearchKey
}

export type ActiveResearchItem = ResearchItem & {
  isUnlocked: boolean
  isVisible: boolean
  prerequisiteName?: BilingualTextValue
}

export type BuildingCounts = Record<BuildingType, number>

export type WorkerType =
  | 'operator'
  | 'mechanic'
  | 'salesAgent'
  | 'chemist'
  | 'logisticsCoordinator'
  | 'safetyOfficer'
  | 'fuelSpecialist'
  | 'aviationSpecialist'
  | 'chemicalEngineer'
  | 'polymerEngineer'

export type WorkerCounts = Record<WorkerType, number>

// --- System 1: Staff Training & Levels (Individual Staff, Phase 1) ---
// Each hired worker is a named Employee with their OWN level (1-5) and XP.
// Level multiplies that employee's bonus effectiveness (see
// getWorkerLevelMultiplier). XP accrues passively via "concentrated
// training" (see applyStaffXp) or can be bought instantly for one employee.
export type Employee = {
  id: string
  type: WorkerType
  name: string
  level: number
  xp: number
  // Phase 4: rare permanent trait rolled at hire time. 'veteran' adds a flat
  // bonus to this employee's effectiveness multiplier (see
  // getEmployeeMultiplier). Extensible for future traits.
  trait?: 'veteran'
  // Phase 5: business year this employee was hired. Used to determine
  // retirement eligibility (see HIRING_BALANCE.retirementAfterYears).
  hiredOnYear?: number
}

// --- System 2: Refinery Upgrade Perk Tree ---
// Spend upgradePoints (earned on refinery level-up) on perks across 3 branches.
export type PerkBranch = 'efficiency' | 'capacity' | 'quality'

export type PerkKey =
  | 'efficiency1'
  | 'efficiency2'
  | 'efficiency3'
  | 'capacity1'
  | 'capacity2'
  | 'capacity3'
  | 'quality1'
  | 'quality2'
  | 'quality3'

export type PerkConfig = {
  key: PerkKey
  branch: PerkBranch
  tier: 1 | 2 | 3
  cost: number
  name: BilingualTextValue
  description: BilingualTextValue
  prerequisite?: PerkKey
}

// --- System 3: Tech Eras ---
export type EraKey = 'foundation' | 'expansion' | 'modern' | 'energyTransition'

export type EraConfig = {
  key: EraKey
  index: number
  name: BilingualTextValue
  tagline: BilingualTextValue
  // Unlock requirements (both must be met to advance into this era)
  requiredResearch: number
  requiredLevel: number
  // Global bonuses granted while in this era
  sellPriceBonusRate: number
  researchRateBonusRate: number
  // Strategic Differentiation #2: if true, this era SHIFTS demand each tick
  // (gasoline demand declines, petrochemicals demand rises) instead of just
  // granting a flat bonus -- see DEMAND_SHIFT_BALANCE.
  demandShift?: boolean
}

// --- System 4: Annual Awards ---
export type AwardGrade = 'S' | 'A' | 'B' | 'C'

// One rival refinery's result for a business year (Annual Ranking).
export type RivalResult = {
  key: string
  name: BilingualTextValue
  score: number
  grade: AwardGrade
}

export type YearStats = {
  gasolineProduced: number
  moneyEarned: number
  contractsCompleted: number
}

export type AwardRecord = {
  year: number
  grade: AwardGrade
  score: number
  cashReward: number
  payroll: number
  netProfit: number
  // True if cash on hand couldn't fully cover payroll this year (a small
  // reputation penalty was applied). Surfaced in the ceremony so the player
  // understands why reputation dropped — previously computed but discarded.
  couldNotAfford: boolean
  // Annual Ranking (Charm Pass follow-up): 3 fictional rivals + the player's
  // rank among all 4. Empty array for records saved before this feature —
  // the ceremony hides the ranking section in that case.
  rivals: RivalResult[]
  playerRank: number
  gasolineProduced: number
  moneyEarned: number
  contractsCompleted: number
}

export type WorkerConfig = {
  key: WorkerType
  name: BilingualTextValue
  cost: number
  description: BilingualTextValue
  unlockLevel?: number
  tier?: 1 | 2 | 3
}

export type ActiveWorkerItem = WorkerConfig & {
  count: number
}

export type RandomEventKey =
  | 'crudeDiscount'
  | 'machineTuneUp'
  | 'minorLeak'
  | 'qualityBonus'
  | 'marketDemandSpike'
  | 'safetyInspection'
  | 'equipmentWear'
  | 'efficientBatch'
  | 'localNewsCoverage'
  | 'supplierDiscount'
  | 'equipmentInspection'
  | 'workerSuggestion'
  | 'storageContamination'
  | 'communityVisit'
  | 'distillationHiccup'
  | 'feedstockSurplus'

export type RandomEvent = {
  key: RandomEventKey
  name: BilingualTextValue
  message: string
  // If true, this event only fires once the player has built distillation
  // (maxFeedstockStorage > FEEDSTOCK_BALANCE.baseFeedstockStorage) — keeps
  // feedstock-chain flavor events from showing up for Tier-1-only players.
  requiresFeedstockChain?: boolean
  // ESG/Safety axis: marks "something went wrong" operational incidents
  // (resource loss from leaks/equipment/contamination). Incident-event
  // selection chance scales with esgScore (see getIncidentChance).
  isIncident?: boolean
}

export type ChoiceEventKey =
  | 'supplierNegotiation'
  | 'researchGrant'
  | 'workerRecruitment'
  | 'equipmentEmergency'
  | 'governmentIncentive'
  | 'qualityAlert'
  | 'supplyChainDelay'
  | 'investorVisit'
  | 'oldEquipmentSale'
  | 'trainingRequest'
  | 'communityComplaint'
  | 'rushOrder'

export type ChoiceEvent = {
  key: ChoiceEventKey
  title: BilingualTextValue
  description: BilingualTextValue
  optionA: BilingualTextValue
  optionB: BilingualTextValue
}

export type ShipmentKey =
  | 'miniDelivery'
  | 'localTruck'
  | 'coastalTanker'
  | 'importedShip'
  | 'tankerConvoy'

export type PendingShipment = {
  id: number
  amount: number
  arrivesAt: number
}

export type StandingOrderKey =
  | 'asphaltMaintenance'
  | 'jetFuelCharter'
  | 'lubricantSupply'
  | 'petrochemExport'
  | 'recyclingContract'
  | 'pelletExport'

export type MilestoneKey =
  | 'firstFuel'
  | 'smallSupplier'
  | 'growingRefinery'
  | 'researchBeginner'
  | 'upgradeBuilder'
  | 'reputedSupplier'
  | 'industrialProducer'
  | 'refineryLevel5'
  | 'researchAdvanced'
  | 'contractVeteran'
  | 'tierThreeContractor'
  | 'fullWorkforce'
  | 'jetFuelPioneer'
  | 'aviationPartner'
  | 'petrochemicalPioneer'
  | 'productMogul'

export type Milestone = {
  key: MilestoneKey
  name: BilingualTextValue
  requirement: BilingualTextValue
  reward: string
}

export type MilestoneProgress = {
  current: number
  target: number
}

export type ActiveMilestone = Milestone & {
  isCompleted: boolean
  // Numeric progress toward the milestone, where computable (most
  // milestones are simple count thresholds). null for milestones whose
  // condition isn't a single number (e.g. "build a Jet Fuel Plant").
  progress: MilestoneProgress | null
}

// In-game calendar clock (day/night cycle + day-of-week/day-of-month),
// derived purely from tickCount. See CALENDAR_BALANCE in data/balance.ts
// for why this is independent of the year/season system.
export type GameClock = {
  hourOfDay: number
  dayOfWeek: number
  dayOfMonth: number
  isDaytime: boolean
}

// --- Hidden Event system ---
// Separate from Hidden Combos (building-adjacency based, see
// HIDDEN_COMBOS) -- these are gated by the in-game calendar clock
// (GameClock above) instead, optionally combined with an in-game state
// condition. Checked every tick; once a config's condition is true AND
// it hasn't been unlocked yet, it becomes a claimable "???" card that
// stays available indefinitely until the player claims it (no deadline,
// no expiry -- see design discussion).
//
// Time conditions are deliberately data-only (not arbitrary functions) so
// they stay simple to read/balance and there's exactly one place
// (getIsTimeConditionMet) that knows how to evaluate them.
export type HiddenEventTimeCondition =
  // True during [startHour, endHour) every in-game day (wraps past
  // midnight if endHour <= startHour, e.g. 22-2 means 22:00-01:59).
  | { type: 'hourRange'; startHour: number; endHour: number }
  // True on one specific day of the week (0-6, see CALENDAR_BALANCE).
  | { type: 'dayOfWeek'; day: number }
  // True on one specific day of the month (0-29).
  | { type: 'dayOfMonth'; day: number }

// In-game state conditions, beyond just timing. Kept to the handful of
// shapes actually needed rather than a generic expression language.
export type HiddenEventGameCondition =
  | { type: 'minRefineryLevel'; level: number }
  | { type: 'minMoney'; amount: number }
  | { type: 'minBuildingCount'; building: BuildingType; count: number }

export type HiddenEventDifficulty = 'easy' | 'medium' | 'hard'

export type HiddenEventReward =
  | {
      kind: 'contract'
      // A fully-formed Contract (see Contract type) that gets added to
      // the player's contract list once unlocked. Shown as "???" (no
      // name/reward/requirement visible) until claimed.
      contract: Contract
    }
  | {
      kind: 'building'
      // A building the player can place for a limited number of uses
      // once unlocked (tracked via GameState.hiddenBuildingUsesRemaining)
      // -- not a permanently-unlocked new BuildingType, since the build
      // picker UI assumes a fixed building list. Reusing BuildingType
      // keeps this additive: cost/effect come from the SAME balance
      // tables as the normal building, this just grants free/discounted
      // placements.
      building: BuildingType
      uses: number
      costOverride?: number
    }
  | {
      kind: 'staff'
      // A one-off named "legendary" hire: a WorkerConfig-shaped employee
      // that gets added directly to GameState.employees once claimed
      // (bypassing the normal recruitment pool/cost), pre-set to a given
      // level and always the 'veteran' trait.
      workerType: WorkerType
      name: string
      startingLevel: number
    }

export type HiddenEventConfig = {
  key: string
  difficulty: HiddenEventDifficulty
  // ALL conditions must be true (AND) for the event to unlock.
  timeConditions: HiddenEventTimeCondition[]
  gameConditions?: HiddenEventGameCondition[]
  name: BilingualTextValue
  // Flavor text shown only AFTER the event is unlocked/revealed.
  revealMessage: BilingualTextValue
  reward: HiddenEventReward
}

export type DerivedStats = {
  activeContracts: ActiveContract[]
  activeMilestones: ActiveMilestone[]
  activeResearchItems: ActiveResearchItem[]
  activeWorkers: ActiveWorkerItem[]
  availableSpace: number
  baseCrudeStorage: number
  baseGasolineStorage: number
  baseProductionInterval: number
  buildingCounts: BuildingCounts
  canProcessCrude: boolean
  comboStats: ComboStats
  maxCrudeStorage: number
  maxGasolineStorage: number
  productionInterval: number
  contractRewardMultiplier: number
  esgContractRewardMultiplier: number
  contractRpRewardMultiplier: number
  reputationContractRewardMultiplier: number
  eventPenaltyMultiplier: number
  reputationTier: ReputationTier
  nextReputationTier?: ReputationTier
  researchProductionMultiplier: number
  researchContractRewardMultiplier: number
  researchSellPriceBonus: number
  researchStorageBonus: number
  specialBuildingContractRewardMultiplier: number
  specialBuildingRpRewardMultiplier: number
  workerProductionMultiplier: number
  // Global product sell multiplier (Sales Agents % + quality perks + era).
  // Applies to every product's sell price.
  productSellMultiplier: number
  workerStorageBonus: number
  // System 2 + 3 derived contributions (already folded into the multipliers
  // above, exposed here for UI display)
  // perkProductionBonusRate now drives gasoline YIELD per batch (Perk
  // Diversity Pass) -- NOT production speed, which hits the
  // minProductionMs floor too early for the Efficiency branch to matter.
  perkProductionBonusRate: number
  perkStorageBonusRate: number
  perkSellPriceBonusRate: number
  currentEra: EraConfig
  nextEra?: EraConfig
  eraSellPriceBonusRate: number
  eraResearchRateBonusRate: number
  // Refinery process chain (feedstock layer)
  maxFeedstockStorage: number
  maxWasteStorage: number
  // Tank Farm (Per-Product Storage, design doc Part B)
  maxLubricantsStorage: number
  maxJetFuelStorage: number
  maxPetrochemicalsStorage: number
  maxRecycledMaterialStorage: number
  maxPlasticPelletsStorage: number
  maxElectricityStorage: number
  electricityDemandPerCycle: number
  feedstockPerDistillationCycle: number
  productionMultiplier: number
  productionRate: number
  progressPercent: number
  sellPrice: number
  seasonalGasolineMultiplier: number
  gameClock: GameClock
  sellPriceMultiplier: number
  statusLabel: BilingualTextValue
  storageMultiplier: number
  upgradeCost: number
}
